AWSTemplateFormatVersion: '2010-09-09'
Description: Creates S3 bucket and DynamoDB backends for Terraform remote storage
Parameters:
  BucketName:
    Type: String
    Description: Used for bucket name
  TableName:
    Type: String
    Description: Used for dynamodb table name
Resources:
  TerraformRemoteStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl:  LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
  TerraformRemoteStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: LockID
        AttributeType: S
      KeySchema:
      - AttributeName: LockID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: !Ref TableName
Outputs:
  TerraformRemoteStateBucket:
    Value: !Ref TerraformRemoteStateBucket
  TerraformRemoteStateTable:
    Value: !Ref TerraformRemoteStateTable
